# Symlink this file to .. if you need it

.PHONY: all clean install build test flake8 mypy static

all: build

clean:
	python3 setup.py clean
	rm -rf build

build:
	python3 setup.py build

install:
	python3 setup.py install --user

test:
	tests/tests.py

static: mypy flake8

mypy:
	python3 -m mypy cxxlookup

flake8:
	python3 -m flake8 cxxlookup
